### ISSUE TITLE
Missing step

### ISSUE THREAD

**Issue by baseband-geek** [baseband-geek/singlepulse-visualizer#1]
Need to add in (either explicitly or replicate the functionality in another way) the step between creating all the .singlepulse files from the pipeline and running these scripts which I used: 
`sort -n -k3,3 -k2r,2  $obs_DM*.singlepulse | uniq > $obs.singlepulse`

**Comment by bwmeyers** [comment]
I suppose it depends on if we want to keep the sorting calls internal to the Python scripts or whether we can call them externally (in which case we can just use os.system() or equivalent to use the unix command).

In terms of the uniq call to just get the unique lines, we could use the "set" functionality in Python.

**Comment by bwmeyers** [comment]
For completeness: see sort_singlepulse function in singlepulse_tools.
